#!/bin/bash
# convert a pdf file into a png
# (at single- and double- resolution)
#
# relies on: gs
#
# USAGE:
#
# # default parameters
# pdf2png2 [filename.pdf]
#
# # non-default resolution
# dpi=75 pdf2webp2 [filename.pdf]
#

FILENAME=$1
EXT="${FILENAME##*.}"
BASENAME="${FILENAME%%.pdf}"

if [[ "${EXT}" != "pdf" ]]; then
  echo "input file must be *.pdf"
  exit 1
fi


# get arguments from environment
if [ -z ${dpi+x} ]; then
    dpi=150
fi


# perform conversion at single and double resolution 
for multiplier in 1 2
do
    resolution=$(($multiplier * $dpi))
    gs -dNOPAUSE -dBATCH -q -sDEVICE=pngalpha \
       -r${resolution}x${resolution} \
       -sOutputFile=${BASENAME}@${multiplier}x.png \
       ${BASENAME}.pdf
done

